// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Copywright © 2026 ZenithClown (Debmalya Pramanik) | https://zenithclown.github.io/ | https://www.linkedin.com/in/dpramanik/

//@version=6

// ==================================================================
// OBJECTTIVE: Create a EMA Cloud from a Pair of EMA Length
//
// EMA Pairs is one of the oldest and most durable form of technical
// indicator which serves various purposes. In this strategy, a pair
// of EMA length is used where one is a "fast" exponential moving
// (which determines the current rhythm of the security) and the other
// is the "slow" exponential moving average (which determines the
// underlying drift in the security).
//
// Example/Usage(s) of EMA Pairs
//
// EMA Pairs serves different purposes. Here are an example of typical
// pairs that are used in institutions, market research and other
// published strategies:
//
// Scalping/Intraday Momentum [5, 13] - Linda Raschke"s Classic Fast
// Pair; Very Reactive. Recommended Timeframe: 5-15 mins. Chart
//
// Short-Term Swing/Intraday Trend [7, 21] - Popular on Crypto and NSE
// (Indian Securities); Catches Multi-Day Momentum.
//
// Short-Term Swing [9, 21] - Slight Variation, Popular on FOREX and
// Futures Desks.
//
// Institutional Gold Standard [50, 200] - The most watched global
// standard. The crossover strategy are (I) "Golden Crossover" when
// the 50 EMA crosses above 200 EMA and (II) "Death Crossover" occurs
// when the 50 EMA falls below the 200 EMA line.
//
// Check https://github.com/growthio/tradingview for details.
// Check https://in.tradingview.com/u/ZenithClown/ for TV Profile.
// ==================================================================

indicator("EMA Cloud", overlay = true)

// ------------------------------------------------------------------
// INPUT(s) for EMA Cloud Pair(s) to Determine Underlying Movement
// ------------------------------------------------------------------

src = input.source(
    close, 'Candle Source', group = 'EMA Pair Settings'
)

fastLength = input.int(
    7, "Fast EMA Length", group = "EMA Pair Settings"
)

slowLength = input.int(
    21, "Slow EMA Length", group = "EMA Pair Settings"
)

bullColor = input.color(
    color.new(color.green, 70), "BULL"
    , group = "Color Settings", inline = "CL"
)

bearColor = input.color(
    color.new(color.red, 70), "BEAR"
    , group = "Color Settings", inline = "CL"
)

neutralColor = input.color(
    color.new(color.yellow, 70), "NEUTRAL"
    , group = "Color Settings", inline = "CL"
)

// ------------------------------------------------------------------
// Import Trading View Library & Get Values
// ------------------------------------------------------------------

import ZenithClown/cloudTheory/2 as cloudTheory

[emaFast, emaSlow, mktSentiment] = cloudTheory.drawCloud(
    fastLength, slowLength, close
)

fillCol = mktSentiment == 1 ? bullColor : mktSentiment == -1 ? bearColor : neutralColor

pFast = plot(emaFast, "Fast EMA", color = color.new(color.black, 20), display = display.none)
pSlow = plot(emaSlow, "Slow EMA", color = color.new(color.black, 20), display = display.none)
fill(pFast, pSlow, color = fillCol, title = "EMA Cloud")

// ------------------------------------------------------------------
// EMA Cloud - Draw the Bearish/Bullish Crossover Indicators
// ------------------------------------------------------------------

upCross = ta.crossover(emaFast, emaSlow)
dnCross = ta.crossunder(emaFast, emaSlow)

plotshape(
    upCross, style = shape.triangleup, location = location.belowbar
    , color = color.black, size = size.tiny, title = "BULL Crossover"
)

plotshape(
    dnCross, style = shape.triangledown, location = location.abovebar
    , color = color.black, size = size.tiny, title = "BEAR Crossover"
)
